export enum CustomProviders {
	CTF_ACCOUNT_SETTINGS_SERVICE = 'CTF_ACCOUNT_SETTINGS_SERVICE',
	CTF_ACCOUNT_SETTINGS_REPOSITORY = 'CTF_ACCOUNT_SETTINGS_REPOSITORY',

	CTF_AUTH_SERVICE = 'CTF_AUTH_SERVICE',

	CTF_CRYPTO_SERVICE = 'CTF_CRYPTO_SERVICE',

	CTF_DIRECT_CHATS_SERVICE = 'CTF_DIRECT_CHATS_SERVICE',
	CTF_DIRECT_CHATS_REPOSITORY = 'CTF_DIRECT_CHATS_REPOSITORY',

	CTF_DIRECT_CHAT_MESSAGES_REPOSITORY = 'CTF_DIRECT_CHAT_MESSAGES_REPOSITORY',

	CTF_EMAIL_SERVICE = 'CTF_EMAIL_SERVICE',

	CTF_THROTTLER_GUARD = 'CTF_THROTTLER_GUARD',

	CTF_JWT_TOKENS_SERVICE = 'CTF_JWT_TOKENS_SERVICE',
	CTF_JWT_TOKENS_REPOSITORY = 'CTF_JWT_TOKENS_REPOSITORY',

	CTF_OTP_CODES_SERVICE = 'CTF_OTP_CODES_SERVICE',
	CTF_OTP_CODES_REPOSITORY = 'CTF_OTP_CODES_REPOSITORY',

	CTF_PASSWORD_RESET_TOKENS_SERVICE = 'CTF_PASSWORD_RESET_TOKENS_SERVICE',
	CTF_PASSWORD_RESET_TOKENS_REPOSITORY = 'CTF_PASSWORD_RESET_TOKENS_REPOSITORY',

	CTF_USERS_SERVICE = 'CTF_USERS_SERVICE',
	CTF_USERS_REPOSITORY = 'CTF_USERS_REPOSITORY',
}
