export enum CustomProviders {
	I_USERS_SERVICE = 'I_USERS_SERVICE',
	I_EMAIL_SERVICE = 'I_EMAIL_SERVICE',
	I_USERS_REPOSITORY = 'I_USERS_REPOSITORY',
	I_ACCOUNT_SETTINGS_REPOSITORY = 'I_ACCOUNT_SETTINGS_REPOSITORY',
	I_OTP_CODES_REPOSITORY = 'I_OTP_CODES_REPOSITORY',
}
