name: Dependencies review
on:
  push:
    branches: ["master", "release/*"]
  pull_request:
    branches: ["master", "release/*"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          license-check: true
          vulnerability-check: true
          comment-summary-in-pr: never
